name: testing

on:
  workflow_call:
    inputs:
      rocm_version:
        type: string
        description: ROCm release version
        required: true
        default: "5.1"
      test_me:
        type: string
        description: Test me
        required: true
        default: "2"



jobs:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout new branch
        uses: actions/checkout@v2
        with:
          ref: master
        run: echo 'zdravo'
        if: ${{ github.event.inputs.rocm_version == false }}
        run: echo 'test me'
     - name: Checkout new branch
        uses: actions/checkout@v2
        with:
          ref: master
        run: echo 'cao'